[default]
path = "/home/antonin/wallpaper"
duration = "15m"
mode = "center"
#sorting = "ascending"

[default.transition.hexagonalize]
# default values for hexagonalize
# steps = 50
# horizontal-hexagons = 20.0
